name: Cross-platform sanity check

on: [ push ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: [ "3.8", "3.9", "3.10", "3.11", "pypy3.9", "pypy3.10" ]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: python -m pip install --upgrade pip setuptools wheel maturin pytest virtualenv
      - name: Create virtualenv and install package
        run: |
          python -m venv env
          source env/bin/activate
          python -m maturin develop --release
      - name: Test
        run: |
          python -m pytest
